server:
  port: 9019

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    username: chen
    password: Cxx910628
    url: jdbc:mysql://rm-3nsdlw9h3uyj02x18ko.mysql.rds.aliyuncs.com:3306/springtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password: cxx910628.
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
#  rabbitmq:
#    host: 47.240.34.64
#    port: 5672
#    username: CC
#    password: cxx910628.
  ssl:
    #    证书路径
    key-store: www.ruirui.fun.jks
    key-store-type: JKS
    key-alias: tomcat
    #    配置密码，就是在生成证书的时候输入的密码
    key-store-password: ppma8l0w779i


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug